
PACKAGE_SUBVER=1

PACKAGEMAKER=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker

VERSION=$(shell cat $(wildcard ../VERSION ../../VERSION) | head -n 1 | sed -e 's/.*(\(.*\)).*/\1/')

